'use client';

import * as MT from '@material-tailwind/react';

export const Button: any = MT.Button;
export const Dialog: any = MT.Dialog;
export const Breadcrumbs: any = MT.Breadcrumbs;
export const Card: any = MT.Card;
export const CardHeader: any = MT.CardHeader;
export const CardBody: any = MT.CardBody;
export const CardFooter: any = MT.CardFooter;
export const Typography: any = MT.Typography;
export const Checkbox: any = MT.Checkbox;
export const Select: any = MT.Select;
export const Option: any = MT.Option;
export const Input: any = MT.Input;
export const Radio: any = MT.Radio;
export const List: any = MT.List;
export const ListItem: any = MT.ListItem;
export const ListItemPrefix: any = MT.ListItemPrefix;
export const IconButton: any = MT.IconButton;
export const Popover: any = MT.Popover;
export const PopoverHandler: any = MT.PopoverHandler;
export const PopoverContent: any = MT.PopoverContent;
export const Textarea: any = MT.Textarea;
export const Navbar: any = MT.Navbar;
export const Collapse: any = MT.Collapse;
export const Chip: any = MT.Chip;
export const Spinner: any = MT.Spinner;
export const DialogHeader: any = MT.DialogHeader;
export const DialogBody: any = MT.DialogBody;
export const DialogFooter: any = MT.DialogFooter;
export const ThemeProvider: any = MT.ThemeProvider;
export const useTheme: any = MT.useTheme;
export const Tooltip: any = MT.Tooltip;
export const Switch: any = MT.Switch;
export const Tabs: any = MT.Tabs;
export const TabsHeader: any = MT.TabsHeader;
export const TabsBody: any = MT.TabsBody;
export const Tab: any = MT.Tab;
export const TabPanel: any = MT.TabPanel;
export type Theme = any;
